---
- name: Java installation
  hosts: all
  vars:
    foo:
      first: "one"
      second: "two"
  tasks:
    - name: Ansible | Print a variable
      debug:
        msg:
          - "The operating system is '{{ ansible_distribution }}' "
          - "{{foo.first}}"
          - "{{foo.second}}"
#ansible-playbook Variables.yml -e @vars.yml(variables playbook name)
cd /etc/ansible/ansible.cfg
to include files
vars_files:
  var.yml
